# Generated by Django 3.1.4 on 2024-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='收入', max_length=100),
        ),
    ]
