# Generated by Django 3.1.4 on 2024-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20240829_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='income', max_length=100),
        ),
    ]
