# Generated by Django 3.1.4 on 2024-09-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_transferrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
